# fly.toml app configuration file
app = "oneuptime-yourname"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  ONEUPTIME_HTTP_PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048

[mounts]
  source = "oneuptime_data"
  destination = "/data"

# PostgreSQL database
[[services]]
  internal_port = 5432
  protocol = "tcp"

  [[services.ports]]
    port = 5432

# Redis cache
[[services]]
  internal_port = 6379
  protocol = "tcp"

  [[services.ports]]
    port = 6379